version: '3'
services:
  messenger:
    command: /bin/sh -c "npm run build:dev && npm run start:dev"
    image: node:10
    working_dir: /opt
    ports:
      - "7175:7175"
    volumes:
      - .:/opt:z
    environment:
      RABBIT_URI: amqp://guest:guest@rabbit
      LOG_LEVEL: debug
    networks:
      - rabbit
      - proxy
      - postgres
networks:
  proxy:
    external:
      name: services_proxy
  rabbit:
    external:
      name: infra_rabbit
  postgres:
    external:
      name: infra_postgres
